# Generated by Django 4.2.10 on 2024-09-12 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investment_app', '0003_alter_investmentaccount_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentaccount',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
